name: quay ci

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build, tag, and push image to Quay
      id: build-image
      env:
        REGISTRY: quay.io
        REPOSITORY: iyuroch/shmem
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker login -u="iyuroch" -p="${{ secrets.QUAY_PASSWORD }}" quay.io
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG . -f Dockerfile
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
